[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "rto_projects"
version = "0.1.0"
description = "A simple, GitHub based repository for data science projects."
dependencies = [
    "tomli",
    "tomli-w"
]
authors = [
    {name = "Mitchell Tillman", email = "mtillman14@gmail.com"}
]
maintainers = [
    {name = "Mitchell Tillman", email = "mtillman14@gmail.com"}
]
readme = "README.md"

[project.scripts]
rto = "rto_projects.cli:app"