[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.ross]
language = "python"
dependencies = []

[project]
name = "ross_cli"
version = "0.1.8"
authors = []
readme = "README.md"
dependencies = [
    "https://github.com/ResearchOS/ross_cli.git",
    "numpy==2",
]
